# Generated by Django 3.1.5 on 2021-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginaccounts', '0004_auto_20210202_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='loginaccounts.Tag'),
        ),
    ]
